model_name: "HuggingFaceTB/SmolLM2-360M-Instruct"
output_col: "intent"  # Can be "intent" or "emotion"
learning_rate: 5e-6
batch_size: 1
gradient_accumulation_steps: 1  # Increase for effective batch size
max_steps: 1
num_generations: 2
max_prompt_length: 256
max_completion_length: 100
max_seq_length: 356